version: '3'
services:
  php:
    image: jimindocker/bjxv2-php-fpm:latest
    volumes:
      - .:/app
    networks:
      - bjxv2
  nginx:
    image: jimindocker/bjxv2-nginx:latest
    volumes:
      - .:/app
    ports:
      - "80:80"
    networks:
      - bjxv2
    depends_on:
      - php
  redis:
    image: redis:6.2.6
    networks:
      - bjxv2

networks:
  bjxv2:


